# AMBARELLA Platform Support
snd-soc-ambarella-objs := ambarella_pcm.o
snd-soc-ambarella-i2s-objs := ambarella_i2s.o

obj-$(CONFIG_SND_AMBARELLA_SOC)		+= snd-soc-ambarella.o
obj-$(CONFIG_SND_AMBARELLA_SOC_I2S)	+= snd-soc-ambarella-i2s.o

# AMBARELLA Machine Support
snd-soc-ipcam-objs := ipcam.o
snd-soc-ambevk-objs := ambevk.o
snd-soc-i1evk-objs := i1evk.o
snd-soc-md800-objs := md800.o
snd-soc-dummy-objs := dummy.o
snd-soc-a5spa2-objs := a5spa2.o

obj-$(CONFIG_IPCAM_BOARD)		+= snd-soc-ipcam.o
obj-$(CONFIG_AMBEVK_BOARD)		+= snd-soc-ambevk.o
obj-$(CONFIG_I1EVK_BOARD)		+= snd-soc-i1evk.o
obj-$(CONFIG_MD800_BOARD)		+= snd-soc-md800.o
obj-$(CONFIG_AMBARELLA_DUMMY_BOARD)	+= snd-soc-dummy.o
obj-$(CONFIG_A5S_PA2_BOARD)		+= snd-soc-a5spa2.o

